source 'https://rubygems.org'


gem 'rails', '4.1.4'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc


gem 'haml-rails'

gem 'devise'

group :development do
    gem 'spring'
    gem 'pry-rails'
    gem 'quiet_assets'
    # gem 'better_errors'
    # gem 'binding_of_caller'
  end

# pg gem allows heroku to work with postgres
# rails_12factor gem allows heroku to serve static assets such as
# images and style sheets
# group :production do
#   gem 'pg', '0.15.1'
#   gem 'rails_12factor', '0.0.2'
# end
